name: CI/CD for Blazor.Avatar

on: [push, pull_request]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Build project (Release)
        run: dotnet build -c Release
      - name: Run tests (Release)
        run: dotnet test --no-build -c Release
  
  release:
    name: Release nuget package
    runs-on: ubuntu-latest
    needs: [build]
    # if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      # - name: Verify commit exists in origin/master
      #   run: >
      #     git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* &&
      #     git branch --remote --contains | grep origin/master
      # - name: Set VERSION variable from tag
      #   run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Pack library
        run: dotnet pack -c Release --output . /p:Version=1.2.3     
